# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'


steps:
- script: 'Get-ChildItem -Path C:\ -Filter dotfuscatorCLI.exe -Recurse -ErrorAction SilentlyContinue -Force'
- script: 'Get-ChildItem -Path D:\ -Filter dotfuscatorCLI.exe -Recurse -ErrorAction SilentlyContinue -Force'

- task: ProvisionDotfuscatorCE@1
  inputs:
    dotfuscatorSN: '262202-391'
    dotfuscatorDistro: '16'
  displayName: "Provision Dotfuscator"

- task: NuGetCommand@2
  inputs:
    command: 'restore'
  displayName: "Restore NuGet Packages"

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '15.0'
    platform: 'Any CPU'
    configuration: 'Release'
    clean: true
    maximumCpuCount: true
    restoreNugetPackages: false
  displayName: "Build Solution"

- task: ProtectWithDotfuscatorCE@1
  inputs:
    configFile: 'Azure Pipelines Test\\Azure Pipelines Test\\DotfuscatorConfig.xml'
  displayName: "Protect With Dotfuscator Community"